
-- ============================================================
-- Beverage Sales & Profitability Analysis
-- Tool     : MS SQL Server (SSMS)
-- Author   : Kamal Singh
-- LinkedIn : linkedin.com/in/kamal-singh-2941ab329
-- GitHub   : github.com/Kamal111222
-- ============================================================
-- Dataset  : Three tables — fact, Location, Product
--            Covers sales, profit, marketing, inventory,
--            expenses and budget data for a beverage company.
-- ============================================================
create database Beverage
use Beverage 

select * from fact
select * from location
select * from Product

--1. Display the number of states present in the LocationTable.
select Count (distinct State) as no_of_states from Location

--------------------------------------------------------------------------------------
--2.How many products are of regular type?
select * from Product where Type='Regular'

select COUNT(*) as cnt from Product where Type='regular'
--------------------------------------------------------------------------------------

--3.How much spending has been done on marketing of product ID 1?
select sum(Marketing) as total_spending from fact where ProductId=1
--------------------------------------------------------------------------------------

--4. What is the minimum sales of a products?
select min(Sales) as min_Sales from fact
--------------------------------------------------------------------------------------

--5. Display the max Cost of Good Sold (COGS).
select MAX(COGS) as max_cogs from fact
--------------------------------------------------------------------------------------

--6. Display the details of the product where product type is coffee. 
select * from Product where Product_Type='Coffee'
--------------------------------------------------------------------------------------

--7. Display the details where total expenses are greater than 40. 
select * from fact where Total_Expenses>40
--------------------------------------------------------------------------------------

--8. What is the average sales in area code 719?
select AVG(Sales) as avg_sales from fact where Area_Code=719
--------------------------------------------------------------------------------------

--9. Find out the total profit generated by Colorado state.
select sum(Profit) as total_profit from fact
     inner join Location
     on fact.Area_Code=Location.Area_Code
where State='Colorado'
--------------------------------------------------------------------------------------

--10. Display the average inventory for each product ID.
select ProductId,avg(Inventory) as avg_inventory from fact
       group by ProductId
       order by ProductId
--------------------------------------------------------------------------------------

--11. Display state in a sequential order in a Location Table.
select distinct State from Location order by State
--------------------------------------------------------------------------------------

--12. Display the average budget Margin of the Product where the average budget margin should be greater than 100.
select ProductId,AVG(Budget_Margin) as avg_budget from fact
        group by ProductId
        having avg(Budget_Margin)>100
--------------------------------------------------------------------------------------

--13. What is the total sales done on date 2010-01-01?
select sum(sales) as total_sales from fact where date='2010-01-01'
--------------------------------------------------------------------------------------

--14. Display the average total expense of each product ID on an individual date.
select ProductId,Date,AVG(Total_Expenses) as avg_te from fact
          group by ProductId,Date
          order by ProductId,Date
--------------------------------------------------------------------------------------

--15. Display the table with the following attributes such as date, productID, product_type, product,
--sales, profit, state, area_code
select Date,Product.ProductId,Product_Type,Product,Sales,Profit,State,Location.Area_Code from fact
        join Location
        on fact.Area_Code=Location.Area_Code
        join Product
        on fact.ProductId=Product.ProductId
--------------------------------------------------------------------------------------

--16. Display the rank without any gap to show the sales wise rank.
select *,dense_RANK() over (Order by Sales desc) as rank_sales from fact
--------------------------------------------------------------------------------------

--17. Find the state wise profit and sales. 
select State,Sum(Profit) as totalProfit,Sum(Sales) as totalSales from Location
         join fact
         on Location.Area_Code=fact.Area_Code
group by State
--------------------------------------------------------------------------------------

--18. Find the state wise profit and sales along with the productname.
select State,Product,Sum(Profit) as totalProfit,Sum(Sales) as totalSales from Location
       join fact
       on Location.Area_Code=fact.Area_Code
       join Product
       on fact.ProductId=Product.ProductId
group by State,Product
order by State,Product

select coalesce(state,'S_State'),coalesce(Product,'S_Product'),Sum(Profit) as totalProfit,Sum(Sales) as totalSales from Location
       join fact
       on Location.Area_Code=fact.Area_Code
       join Product
       on fact.ProductId=Product.ProductId
group by rollup( State,Product)
order by State,Product
--------------------------------------------------------------------------------------

--19. If there is an increase in sales of 5%, calculate the increasedsales.
select Sales,sales*1.05 as increasedsales from fact
--------------------------------------------------------------------------------------

--20. Find the maximum profit along with the product ID and producttype. 
select fact.ProductId,Product_Type,max(Profit) as max_profit from fact
       join Product
       on fact.ProductId=Product.ProductId
Group by fact.ProductId,Product_Type
--------------------------------------------------------------------------------------

--21. Create a stored procedure to fetch the result according to the product type from Product Table. 


create procedure product_pt @pt varchar(50)
as
begin
select * from Product where Product_Type=@pt
end

exec product_pt 'Tea'
--------------------------------------------------------------------------------------

--22. Write a query by creating a condition in which if the total expenses is lessthan 60 then it is a profit or else loss. 
select *,
      Case when Total_Expenses<60 then 'Profit'
           else 'Loss'
end as profit_loss
from fact
--------------------------------------------------------------------------------------

--23. Give the total weekly sales value with the date and product IDdetails. Use roll-up to pull the data in hierarchical order.
--Datepart
select DATEPART(WEEK,Date) as weekno,ProductId as ProductId,sum(Sales) as totalSales from fact
group by rollup(DATEPART(WEEK,Date),ProductId) -- 4 means subtotal

select Coalesce(DATEPART(WEEK,Date),4) as weekno,Coalesce(ProductId,4) as ProductId,sum(Sales) as totalSales from fact
group by rollup(DATEPART(WEEK,Date),ProductId) -- 4 means subtotal

select Coalesce(Cast(DATEPART(WEEK,Date) as varchar),'SWeekNo') as weekno,Coalesce(CAST(ProductId as varchar),'Spid') as ProductId,sum(Sales) as totalSales from fact
group by rollup(DATEPART(WEEK,Date),ProductId)
--------------------------------------------------------------------------------------

--24. Apply union and intersection operator on the tables which consist of attribute area code.
select Area_Code from fact
union
Select area_code from Location

select Area_Code from fact
intersect
Select area_code from Location
--------------------------------------------------------------------------------------

--25. Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference.
create function selpt(@pt varchar(50))
returns table
as
return (Select * from Product where Product_Type=@pt)

select * from selpt('Coffee')
--------------------------------------------------------------------------------------

--26. Change the product type from coffee to tea where product IDis 1 and undo it.
select * from Product

begin transaction

   update Product
   set Product_Type='Tea'
   where ProductId=1 and Product_Type='Coffee'

rollback
--------------------------------------------------------------------------------------

--27. Display the date, product ID and sales where total expenses are between 100 to 200.
select date,ProductId,Sales from fact where Total_Expenses between 100 and 200
--------------------------------------------------------------------------------------

--28. Delete the records in the Product Table for regular type.
select * from Product
delete from Product
where Type='Regular'
--------------------------------------------------------------------------------------

--29. Display the ASCII value of the fifth character from the column Product
select * from Product
select Product,ascii(SUBSTRING(Product,5,1)) as AsciiValue from Product
select ascii('A')
--------------------------------------------------------------------------------------
